### ISSUE TITLE
Support LXD 4.0 virtual machines

### ISSUE THREAD

**Issue by jgraichen** [terraform-lxd/terraform-provider-lxd#202]
LXD 4.0 introduced virtual machine support. A new "instances" API had been added to manage containers and virtual machines using a uniform interface. I'd like to have the ability to manage LXD virtual machines with this provider too.

A very small quick fix would be adding a type field to `lxc_container` resources and using the new API (draft available in [00c38a8](https://github.com/jgraichen/terraform-provider-lxd/commit/00c38a8f2284d70e7e601fdf68449a0a6d952c19)). It does look a bit funny to schedule `lxd_container` resources that are of type "virtual-machines", though.

Another idea would be to add a new resource mirror the unified API e.g. `lxd_instance`. It might be a chance to change other things in non-compatible way, e.g. the `config = {}` behavior.

I'd like to invest some time and contribute but would be interested to have this coordinated with the maintainers and how the provider should evolve.

**Comment by jgraichen** [comment]
> Since there is a dedicated API for instances, this is the best way to go.

It is not a standalone API for virtual machines, it is a new API to manage containers & virtual machines (https://lxd.readthedocs.io/en/latest/rest-api/#instances-containers-and-virtual-machines). This API creates virtual machines just like containers based on an additional `type = container | virtual-machine` attribute. Both instance types support the same configuration options, etc.

Having a single resource for containers and virtual machines means the wished type can be specified as an attribute, e.g. like this:

```
resource "lxd_instance" "test" {
  name = "test"
  type = "virtual-machine"
}
```

This is quite nice because it is easy to switch between containers and virtual machines without having to change the resource type. It could very well replace "lxd_container", or we could, similar to the LXD API expose three resources, `lxd_container`, `lxd_virtual_machine` and `lxd_instance`, but I would not like that.

> ~ It might be a chance to change other things in non-compatible way, e.g. the config = {} behavior.
> Which issue is this?

I am not sure. There was a discussion somewhere if changes to `config` should force a recreation of a container or not. I myself had issues a few time with changed config values but not wanting to recreate the container. I applied the changes manually to have it in sync again.

**Comment by jtopjian** [comment]
> It is not a standalone API for virtual machines, it is a new API to manage containers & virtual machines

Right, understood.

I haven't read the API in detail nor looked up the actual function calls in the LXD library, so I might be missing key information.

With creating containers, there was both REST API endpoints and Go code in the LXD client library (example: https://github.com/sl1pm4t/terraform-provider-lxd/blob/master/lxd/resource_lxd_container.go#L268) to create containers. Side note: this provider doesn't interact with LXD via a REST library. It uses the LXD client library bundled in the main LXD code repository.

Given functions such as `CreateContainerFromImage` [still exist](https://github.com/lxc/lxd/blob/e5625c74c3fb24654c46e8e7eb9c87530962ee94/client/lxd_containers.go#L226), then the `lxd_container` resource is still functional, even in LXD 4.0 and up where there is the new "Instances" API.

I'm assuming that there are new REST API calls and LXD client library functions to handle the new instance stuff (co-managing both virtual machines and containers). Using these functions in a new `lxd_instance` resource and continuing to have `lxd_container` still exist and use the "old" functions is the better design, rather than shoe-horning the new Instance stuff in `lxd_container` while trying to keep compatibility with anyone running LXD earlier than 4.0.

> It could very well replace "lxd_container",

Yes, though we'd keep `lxd_container` around indefinitely, especially for users running LXD earlier than 4.0.

>  or we could, similar to the LXD API expose three resources, lxd_container, lxd_virtual_machine and lxd_instance, but I would not like that.

Agreed. I am fine with `lxd_container` using the original container-only API / library functions and `lxd_instance` leveraging the new instance API/ library functions.

> There was a discussion somewhere if changes to config should force a recreation of a container or not. 

ah - right. The debate was around stability of changing, say, the amount of cpus or memory of a running container. I think enough time has passed that there are no longer concerns of that stability. As well, Terraform design best-practices are more leaning towards being a proxy to the API and not instilling opinionated policies (in other words: if the API allows it, Terraform should, too).

We could easily make these changes to `lxd_container` without it being a breaking change.

**Comment by jgraichen** [comment]
The LXD client practically has three exact copies of the same API. Except for the `type` field they are identical. The LXD client actually falls back to the container REST API if using the instances golang API if the server is old:

```go
	// If the remote server doesn't support instances extension, check that only containers
	// or any type has been requested and then fallback to using the old /containers endpoint.
	if !r.HasExtension("instances") {
		if instanceType == api.InstanceTypeContainer || instanceType == api.InstanceTypeAny {
			return "/containers", v, nil
		}

		return "", v, fmt.Errorf("Requested instance type not supported by server")
	}
```

They do not even wrap anything but just use a different path.

Method are just copied, as seen in the very small [diff](https://github.com/jgraichen/terraform-provider-lxd/commit/00c38a8f2284d70e7e601fdf68449a0a6d952c19):

* `CreateContainerFromImage` -> `CreateInstanceFromImage`
* `ContainerStatePut` -> `InstanceStatePut`

For testing I only renaming all method names and it instantly worked. The original method just runs everything with an implicit `type=container`. I'll probably change this nevertheless to reuse all helpers for both resources.

Thanks for the input. I will play with it and try a few things in the next few weeks.

**Comment by 6aKa** [comment]
Will this functionality be implemented?

**Comment by jgraichen** [comment]
Shall we close this issue as #215 is merged and handle `config` changes or a new resource separately?

**Comment by jtopjian** [comment]
Sure, sounds good to me.

**Comment by adamcstephens** [comment]
Thanks for getting this updated and released. I successfully used it over the weekend.
