### ISSUE TITLE
lxd_container_file does not upload the file to container

### ISSUE THREAD

**Issue by imanazari70** [terraform-lxd/terraform-provider-lxd#237]
Versions
Terraform: 1.0.4
LXD Provider: 1.5.0 (latest download from releases' page)
Terraform Driver Machine: ubuntu16.04
LXDHost Machine: Ubuntu 16.04 (LXD: 2.0.11)

resource lxd_container_file does not work.

The following doesn't work:

resource "lxd_container_file" "postinstall" {
  container_name     = "${lxd_container.mylxd1.name}"
  content            = "${file("postinstall")}"
  target_file        = "/opt/postinstall.2"
  uid                = 0
  gid                = 0
  mode               = "0755"
  create_directories = "true"
}

error message is:

unable to create file /opt/postinstall.2: clould not upload file /opt/postinstall.2: the server is missing the required "directory_manipulation" API extention.

**Comment by jtopjian** [comment]
This error looks to be an LXD configuration issue rather than a Terraform issue. It appears that `directory_manipulation` is an [API extension](https://linuxcontainers.org/lxd/docs/master/api-extensions). 

If you're using Ubuntu 16.04 and LXD 2.0.11, maybe it's too old of a version and does not have this API extension?

**Comment by imanazari70** [comment]
I was able to fix this problem by upgrading lxd to version 3.1.
thanks.
