### ISSUE TITLE
Question: what is the order of commands execution in the "execs" block?

### ISSUE THREAD

**Issue by tregubovav-dev** [terraform-lxd/terraform-provider-lxd#486]
Could you please clarify the order of commands execution in the `execs` block in the `lxd_instance` resource? Is it:
- order elements defined in `execs` block?
- alphabetic order?
- undetermined?

**Comment by MusicDin** [comment]
`execs` field within an instance is a map of commands. Commands are executed in order sorted alphabetically by the map key.

**Comment by tomponline** [comment]
@MusicDin how does one go about do execs in a specific order?

**Comment by MusicDin** [comment]
Commands ordered is determined by the map keys. They are sorted alphabetically and executed one by one. Command will be executed only when it is enabled (defaults to `true`), the *trigger* condition is met, and the instance is running (or just being started).

For example:
```
resource "lxd_instance" "inst" {
  name    = "c1"
  image   = "ubuntu-daily:22.04"
  running = true

  execs = {
    "99_some_command" = {
      command = ["sh", "-c", "..."]
    }
    
    "50_cloud_init_wait" = {
      command = ["cloud-init", "status", "--wait"]
      trigger = "on_start"
    }
  }
}
```

In the above example, the command `50_cloud_init_wait` is executed first, and then `99_some_command`. 

Just for the demonstration, when reapplying the configuration, the command `50_cloud_init_wait` will be checked first, but because instance is already started (running) it will be skipped as *trigger* is not satisfied. Therefore, only `99_some_command` will be executed. However, the order in which the commands are processed is always the same.

**Comment by MusicDin** [comment]
Here is also the documentation: https://registry.terraform.io/providers/terraform-lxd/lxd/latest/docs/resources/instance#executing-commands-in-instances

The order of command is explained in example section, but should be also emphasized in the `Argument reference` section.

**Comment by tregubovav-dev** [comment]
Thank you Din and Tom for the clarification.

Before asking the question I've tested the similar solution as Din proposed and it's worked. Now I have the final confirmation from you 👍 
Would be nice to mention that in the documentation.

**Comment by tomponline** [comment]
Thanks @MusicDin !
